# Python

In [2]:
import sys
sys.executable 

import numpy as np

In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [5]:
#creating array
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [6]:
arr2D = np.array([[1,2,3,4],[1,2,3,4]])
arr2D

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## Some Imp func

In [7]:
arrZeroes = np.zeros(5) #1d array with 0.
arrZeroes

array([0., 0., 0., 0., 0.])

In [8]:
a4 = np.eye(3) #2d Array with diagonal elemnt 1

In [9]:
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr5 = np.ones((3,3))

In [11]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr4 = np.arange(10) #create single dimesion arra till range 10
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr5 = np.arange(1,10,2) #this works a rnage

In [15]:
arr5

array([1, 3, 5, 7, 9])

In [16]:
arr6 = np.linspace(1,10,5) #start from 1 to 10 and equal ditribute 
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr8 = np.full((3,3),9) #3*3 ka 2d Array with vaule 9
arr8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
r1 = np.random.rand(3,3)#it gives matrix of 3*3 with random betn 0 to 1
r1

array([[0.67963295, 0.6698651 , 0.20245163],
       [0.50064498, 0.74371785, 0.57224489],
       [0.20733881, 0.09215565, 0.58009651]])

In [19]:
r2 = np.random.rand(5)
print(r2)

[0.61566788 0.72051482 0.2637195  0.23887441 0.55598394]


In [24]:
r3 = np.random.randint(3,10) #it give any number betn range

In [25]:
r3

9

In [26]:
r3

9

In [27]:
r3

9

In [28]:
r5 = np.random.randint(2,10,3)#between 2 to 10 and 3 ele
r5

array([3, 6, 5])

In [29]:
r6 = np.random.randint(3,10,(3,3))#betn 3 to 10 random number mke 3,3 mat
r6

array([[5, 9, 3],
       [6, 4, 3],
       [8, 5, 7]])

In [30]:
#Indexing
print(r6[1][2])
print(r6[1,2])


3
3


In [33]:
arr2d = np.random.randint(1,20,(3,3))
arr2d

array([[14,  4,  9],
       [ 6, 14, 13],
       [ 3, 11,  4]])

In [34]:
arr2d

array([[14,  4,  9],
       [ 6, 14, 13],
       [ 3, 11,  4]])

In [39]:
#slicing
arr2d[0:2,2]#2d slicing [rowstart:rowend,colstart:colend]
arr2d[1:2,1:2]#2d get middle elem
arr2d[2:3,1:2]#this we last row and middle ele

array([[11]])

# Shape,Size, and DataType of Array

In [40]:
a3 = np.array([1,2,3,4,5,6])
a3.shape

(6,)

In [43]:
a4 = np.random.randint(1,20,(3,3))
a4.shape

(3, 3)

In [45]:
a4.size

9

In [46]:
a4.dtype

dtype('int64')

# Mathematical operations

In [51]:
a1 = np.random.randint(1,10,(1,6))

In [53]:
a2 = np.random.randint(11,20,(1,6))

In [54]:
a2

array([[16, 11, 14, 19, 14, 17]])

In [55]:
print(a1*a2)

[[48 66 70 57 84 17]]


In [56]:
a1+a2

array([[19, 17, 19, 22, 20, 18]])

In [57]:
a1/a2

array([[0.1875    , 0.54545455, 0.35714286, 0.15789474, 0.42857143,
        0.05882353]])

In [58]:
a1 - a2

array([[-13,  -5,  -9, -16,  -8, -16]])

In [59]:
np.sqrt(a1)

array([[1.73205081, 2.44948974, 2.23606798, 1.73205081, 2.44948974,
        1.        ]])

In [60]:
np.square(a1)

array([[ 9, 36, 25,  9, 36,  1]])

In [61]:
arr2d = np.random.randint(1,20,(3,3))
arr2d

array([[18, 11,  2],
       [13,  3,  4],
       [ 5,  6, 12]])

In [62]:
arr2d2 = np.random.randint(20,40,(3,3))
arr2d2

array([[28, 35, 29],
       [38, 29, 34],
       [21, 38, 34]])

In [63]:
np.vstack((arr2d2,arr2d)) #both array combined and arraged in veritcal

array([[28, 35, 29],
       [38, 29, 34],
       [21, 38, 34],
       [18, 11,  2],
       [13,  3,  4],
       [ 5,  6, 12]])

In [64]:
np.hstack((arr2d,arr2d2))#both arr combin and arrage horizontal

array([[18, 11,  2, 28, 35, 29],
       [13,  3,  4, 38, 29, 34],
       [ 5,  6, 12, 21, 38, 34]])

In [65]:
arr2d2.flatten() #2array convert in 1d array flatten

array([28, 35, 29, 38, 29, 34, 21, 38, 34])

# Splitting Array

In [84]:
arr = np.array([1,2,3,4,5,6])
arr2 = np.split(arr,3)
arr2

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arrfinal = np.random.randint(1,10,6) #from, end, size
arr1 = np.split(arrfinal, 3)
print(arr1)
arrfinal

[array([7, 5]), array([1, 2]), array([7, 8])]


array([7, 5, 1, 2, 7, 8])

In [97]:
arr2d = np.random.randint(1,20,(2,4))
arr2d

array([[ 3,  4, 18,  4],
       [ 1, 13, 17,  5]])

In [100]:
arrsplit2d = np.split(arr2d,2)
arrsplit2d

[array([[ 3,  4, 18,  4]]), array([[ 1, 13, 17,  5]])]

In [102]:
arrhsplit = np.hsplit(arr2d,2)
arrhsplit

[array([[ 3,  4],
        [ 1, 13]]),
 array([[18,  4],
        [17,  5]])]

In [107]:
arrvsplit = np.vsplit(arr2d, 2)
arrvsplit

[array([[ 3,  4, 18,  4]]), array([[ 1, 13, 17,  5]])]

# Searchig in array

In [108]:
arr2 = np.array([1,2,3,4,5,6])
np.where(arr2 == 4)

(array([3]),)

In [109]:
np.where(arr2 > 4)

(array([4, 5]),)

In [ ]:
arr2d = np.array([[1,2,3],
                  [2,5,6],
                  [7,8,2]])

In [118]:
np.where(arr2d == 2)

(array([0, 1, 2]), array([1, 0, 2]))

# Sorting in Array

In [119]:
arrUnsort = np.random.randint(1,10,(3,3))#this 3,3 array

In [120]:
arrUnsort

array([[6, 8, 7],
       [7, 9, 8],
       [8, 1, 7]])

In [ ]:
np.sort(arrUnsort)#by deafult in 2d array it sort every row in asc order

array([[6, 7, 8],
       [7, 8, 9],
       [1, 7, 8]])

In [125]:
np.sort(arrUnsort, axis=0) #this applying asix this sort by col in asc

array([[6, 1, 7],
       [7, 8, 7],
       [8, 9, 8]])

In [ ]:
np.sort(arrUnsort, axis=0) #this sort by col wise and reverse 

array([[7, 1, 6],
       [7, 8, 7],
       [8, 9, 8]])