# Python

## Python

In [16]:
import sys
print(sys.executable)

# !{sys.executable} -m pip install numpy (to install numpy)



/usr/local/bin/python3.13
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 764.9 kB/s  0:00:21m0:00:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python3.13 -m pip install --upgrade pip


In [19]:
import numpy as np

dir(np)



[1 2 3 4]


# Creating Array

In [20]:

array1 = np.array([1,2,3,4])
print(array1)

[1 2 3 4]


## 2D array

In [21]:
array2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
a3 = np.zeros(5)
print(a3)

[0. 0. 0. 0. 0.]


In [25]:
a4 = np.eye(3) #2 array create with digonal elemnt 1
print(a4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
arr5 = np.ones((3,3)) #3 by 3 array with all value 1
print(arr5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
arr4 = np.arange(10) #this create 0 to 9 range
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr5 = np.arange(1,11,2) #start, stop, step
print(arr5)

[1 3 5 7 9]


In [29]:
arr6 = np.linspace(1,10,5) #start from 1 to 10 and equal ditribute by 5
print(arr6)

[ 1.    3.25  5.5   7.75 10.  ]


In [30]:
arr8 = np.full((3,3),9) #matrix size 3*3 and value was 9 only
print(arr8)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [32]:
r1 = np.random.rand(3,3)#it gives matrix of 3*3 with random betn 0 to 1 
print(r1)

[[0.46243396 0.12052085 0.83134042]
 [0.55403154 0.58943891 0.95901667]
 [0.20583918 0.07762381 0.04247159]]


In [33]:
r2 = np.random.rand(5) #it give 1D arry from 0 to 1 digit
print(r2)

[0.16517205 0.44013659 0.79929717 0.04476449 0.20982802]


In [35]:
r3 = np.random.randint(5) #it give any number with give range
print(r3)

3


In [36]:
r4 = np.random.randint(3,10) #it give any numbet betn range
print(r4)

6


In [37]:
r5 = np.random.randint(3,10,3)#betn 3 to 10 any 3 number of lst
print(r5)

[4 9 8]


In [38]:
r6 = np.random.randint(3,10,(3,3))#betn 3 to 10 randon number mke 3*3 matrix
r6 

array([[7, 3, 8],
       [7, 6, 7],
       [6, 5, 7]])

In [39]:
r6[0][1]

np.int64(3)

In [42]:
print(r6[1][2]) #or 
print(r6[1,2]) #indexing

7
7


In [62]:
arr2D = np.array([[7, 3, 8],
       [7, 6, 7],
       [6, 5, 7]])
#arr2D[0:2, 2] #[row,column][0:2(means 0 upto 2), 2nd col means 0,1,2]
#arr2D[0:1,1] #3
arr2D[0:2, 2]

array([8, 7])

In [63]:
arr2D[0:2,1]

array([3, 6])

# Shape, Size, and DataType of Array 

In [65]:
a3 = np.array([1,2,3,4,5,6])
print(a3.shape)

(6,)


In [66]:
a4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a4.shape

(3, 3)

In [67]:
a3.size

6

In [68]:
a4.size

9

In [ ]:
a3.dtype #1D array 

dtype('int64')

In [ ]:
a4.dtype #2D array

dtype('int64')

# Mathematical Operations

In [ ]:
a1 = np.array([10,11])
a2 = np.array([5,14])
print(a1 + a2) #sum of both array
print(a1 * a2) #multiply of both array
print(a1 / a2) #division of both array
print(a1 - a2) #subtract of bith array
print(np.sqrt(a1)) #sqrt of a1 array
print(np.square(a1)) #sqaure of a1 array
ans = a1 ** 2
print(ans)
print(np.floor(a1))
print(np.ceil(a1))
print(np.round(a1))
print(np.concatenate((a1,a2))) #combine two array

[15 25]
[ 50 154]
[2.         0.78571429]
[ 5 -3]
[3.16227766 3.31662479]
[100 121]


## Mathematical operation on 2D array

In [ ]:
arr1a2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2a2D = np.array([[9,8,7],[6,5,4],[3,2,1]])

print(np.vstack((arr1a2D,array2D)))#this create vertical stack
print(np.hstack((arr1a2D, arr2a2D)))#this create horizontal sys
print(arr1a2D.flatten())#flatten an array
print()
