# Splitting Array

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
arr2 = np.split(arr,3)
print(arr2)#it equally split arr into proper 4 equal part in 2D array

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr2D = np.array([[1,2,3,4],
                  [5,6,7,8]])
np.hsplit(arr2D, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [9]:
np.vsplit(arr2D, 2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

# Searching in array

In [ ]:
arr1 = np.array([1,3,5,6,8,9])
np.where(arr1 == 9)#return index of element in tuple of list format

(array([5]),)

In [ ]:
np.where(arr1 > 3) #return index value of where element > 3

(array([2, 3, 4, 5]),)

In [14]:
arr2d = np.array([[1,2,3],[2,5,6],[7,8,2]])
arr2d

array([[1, 2, 3],
       [2, 5, 6],
       [7, 8, 2]])

In [ ]:
np.where(arr2d == 2)#it gives the position of where element found in where first list give rows, 2nd col

(array([0, 1, 2]), array([1, 0, 2]))

# Sorting of Array

In [16]:
a1 = np.array([4,3,2,1])
np.sort(a1)

array([1, 2, 3, 4])

In [36]:
a2d = np.array([[3, 2, 1],
                [6, 5, 2],
                [7, 8, 2]])
a2d

array([[3, 2, 1],
       [6, 5, 2],
       [7, 8, 2]])

In [38]:
np.sort(a2d)#it short every single row in asc

array([[1, 2, 3],
       [2, 5, 6],
       [2, 7, 8]])

In [19]:
a2d[::-1]

array([[7, 8, 2],
       [2, 5, 6],
       [1, 2, 3]])

In [ ]:
# find how to sort in descending order
np.sort(a1)[::-1]#1d array sort

#2D array sort
np.sort(a2d)[::-1][:,::-1] #reverse 2D array
#rvrs_arr[:,::-1] #reverse and sort each row in desc

# find how to sort col-wise & row-wise
np.sort(a2d)[::-1,:]#col wise sort in desc
np.sort(a2d)[:,::1]#col wise sort in asc

np.sort(a2d)#row-wise sort in asc
np.sort(a2d)[:,::-1]#row-wise sort in desc
#           [col,row]

array([[3, 2, 1],
       [6, 5, 2],
       [8, 7, 2]])

In [39]:
np.argsort(a2d)

array([[2, 1, 0],
       [2, 1, 0],
       [2, 0, 1]])

# Aggregating & statistical Function

In [62]:
a1 = [5,5.5,6,4,7,2,8]
np.sum(a1)

np.float64(37.5)

In [63]:
np.mean(a1)

np.float64(5.357142857142857)

In [64]:
np.median(a1) #first sort the values and pick the middle one

np.float64(5.5)

In [65]:
np.min(a1)

np.float64(2.0)

In [66]:
np.max(a1)

np.float64(8.0)

In [67]:
(6-9)**2+(7-9)**2+(8-9)**2+(9-9)**2+(10-9)**2+(11-9)**2

19

In [68]:
19/6


3.1666666666666665

In [69]:
#var = 4
#sd = sqrt(var)
arr2 = [6,7,8,9,10,11]
np.std(arr2)

np.float64(1.707825127659933)

In [72]:
varianceValue = np.var(arr2)

In [ ]:
print(np.sqrt(varianceValue)) #correct 

1.707825127659933


In [ ]:
a2d = np.array([[3, 2, 1],
                [6, 5, 2],
                [7, 8, 2]])
np.sum(a2d, axis=1)#row sum

array([ 6, 13, 17])

In [76]:
np.sum(a2d,axis=0)#col sum

array([16, 15,  5])

In [83]:
#check if all aggregation & statistical function have "axis"
print(np.mean(a2d, axis=1))#mean of each row
print(np.mean(a2d, axis=0))#mean of each col
print(np.var(a2d, axis=1))#var of each row
print(np.std(a2d,axis=1))#std of each row
print(np.median(a2d, axis=1))#medain of each row
# parameter to work with 2d array ?
# help(np.std())

[2.         4.33333333 5.66666667]
[5.33333333 5.         1.66666667]
[0.66666667 2.88888889 6.88888889]
[0.81649658 1.69967317 2.62466929]
[2. 5. 7.]
