# Boolean Indexing (Filtering Array)

In [3]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
#Array og Boolean (Boolean Indexing)
l = [True, False, True, False, True]
arr[l] #here I am getting True value

array([1, 3, 5])

In [ ]:
# l2 = (arr%2==0)#the
# l2

array([False,  True, False,  True, False])

In [8]:
arr[arr%2==0]

array([2, 4])

In [11]:
arr[arr > 3]

array([4, 5])

# Boolean Mask (Masking Array)

In [ ]:
arr1 = np.array([10,12,13,14,15])
m = arr1%2==0 #this get true if num is disible by 2
m

array([ True,  True, False,  True, False])

In [ ]:
np.ma.array(arr1,mask=m)#from here falsy get and truthy become --

masked_array(data=[--, --, 13, --, 15],
             mask=[ True,  True, False,  True, False],
       fill_value=999999)

In [21]:
odd_number = np.ma.array(arr1, mask=arr1%2!=0)
print(odd_number)

[10 12 -- 14 --]


# Reshaping Array

In [23]:
arr4 = np.random.randint(3,10,(3,3))
arr4

array([[5, 3, 7],
       [8, 6, 6],
       [7, 9, 8]])

In [24]:
arr4.flatten()

array([5, 3, 7, 8, 6, 6, 7, 9, 8])

In [ ]:
arr4.reshape(-1)#convert multidimesional into 1D

array([[5, 3, 7],
       [8, 6, 6],
       [7, 9, 8]])

In [27]:
arr4.ravel() #convert Multi-dimensional array into 1D array

array([5, 3, 7, 8, 6, 6, 7, 9, 8])

In [4]:
ar1D = np.arange(12)

In [29]:
ar1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ar1D.reshape(4,3) #4rows and 3Cols

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
ar1D.reshape(2,-1) # -1 means automatically decides the possible dimension


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
ar1D.reshape(-1,3) #-1 means automaticaaly decide the possible dimnesions

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])