# Numpy Analyzer

In [ ]:
import numpy as np
class DataAnlytics():
    def __init__(self):
        self.array = None
        
    #_____Private Method______
    def _validateShape_Size(self,arr2):
        return np.size(self.array) == np.size(arr2) and np.shape(self.array) == np.shape(arr2)
    #____Static Method_____
    @staticmethod
    def show_menu():
        print("""
        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        """)
        
    def create_array(self):
        print('''Select type of Array to Create:
              1.1D array
              2.2D array
              3.3D array
              ''')
        choice = int(input("Enter your choice: "))
        #1D Array
        if choice == 1:
            self.array = np.array(list(map(lambda a: int(a),input("Enter a numb").split(" "))))
            
        #2D Array
        elif choice == 2:
            row = int(input("Enter Row"))
            col = int(input("Enter col"))
            enterElemt = row * col
            
            lst = list(map(int, input(f"Enter value:{enterElemt} ").split(" ")))
            self.array = np.array(lst).reshape(row, col)
        
        #3D array
        elif choice == 3:
            noOf2Ddep = int(input("Enter no. of depth: "))
            noOfRow = int(input("Enter no. of rows: "))
            noOfCol = int(input("Enter no. of cols: "))
            expectValue = noOfRow * noOfCol
            
            matrix3D = []
            
            for i in range(noOf2Ddep):
                lst = list(map(int, input(f"Enter value:depth{i} {expectValue}").split(" ")))
                arr2d = np.array(lst).reshape(noOfRow,noOfCol)
                matrix3D.append(arr2d)
            
            self.array = np.array(matrix3D)
        else:
            print("\nInvalid Choice")
        
        print("\nCreated Array:\n", self.array)
    
    def get_array(self):
        return self.array
    
    def math_operations(self,arr2):
        
        if(self._validateShape_Size(arr2)):
            print('''
                  Choose Mathematical Operation
                  1.Addition 
                  2.Subtraction
                  3.multiplication
                  4.Division
                  5.Dot Product
                  6.Matrix Multiplication
                  ''')
            choiceOfOperation = int(input("Enter a operation: "))
            if choiceOfOperation == 1:
                return self.array + arr2
            elif choiceOfOperation == 2:
                return self.array - arr2
            elif choiceOfOperation == 3:
                return self.array * arr2
            elif choiceOfOperation == 4:
                return self.array / arr2
            elif choiceOfOperation == 5:
                return np.dot(self.array,arr2)
            elif choiceOfOperation == 6:
                return np.matmul(self.array, arr2)
            else:
                return "Invalid"
        else:
            return "Shape And Size was not Same"
            
    def search_sort_filter(self):
        print('''
              Choice of operation
              1.Search
              2.Sort
              3.Filter
              ''')
        choiceOfSearchSortFil = int(input("Enter a choice: "))
        if choiceOfSearchSortFil == 1:
            valueSearch = int(input("Enter a value: "))
            return np.where(self.array == valueSearch)
        elif choiceOfSearchSortFil == 2:
            return np.sort(self.array)
        elif choiceOfSearchSortFil == 3:
            enterValueFil = int(input("Enter the number: "))
            return self.array[self.array > enterValueFil]
        else:
            return "Invalid Input"
    
    def aggregations(self):
        return {
            "min": np.min(self.array),
            "max": np.max(self.array),
            "mean": np.mean(self.array),
            "sum": np.sum(self.array),
            "variance": np.var(self.array),
            "std_dev": np.std(self.array),
            "median": np.median(self.array)
        }
        
def main():
    obj = DataAnlytics()

    while True:
        DataAnlytics.show_menu()
        choice = int(input("Enter choice: "))

        if choice == 1:
            obj.create_array()

        elif choice == 2:
            print("Create second array:")
            obj2 = DataAnlytics()
            obj2.create_array()
            result = obj.math_operations(obj2.array)
            print("Result:\n", result)

        elif choice == 3:
            result = obj.search_sort_filter()
            print("Result:\n", result)

        elif choice == 4:
            result = obj.aggregations()
            for k, v in result.items():
                print(f"{k}: {v}")

        elif choice == 5:
            print("Exiting...")
            break

        else:
            print("Invalid choice")

main() 


        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


Enter choice:  1


Select type of Array to Create:
              1.1D array
              2.2D array
              3.3D array
              


Enter your choice:  3
Enter no. of depth:  2
Enter no. of rows:  2
Enter no. of cols:  2
Enter value:depth0 4 1 2 3 4
Enter value:depth1 4 1 2 3 4



Created Array:
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


Enter choice:  2


Create second array:
Select type of Array to Create:
              1.1D array
              2.2D array
              3.3D array
              


Enter your choice:  3
Enter no. of depth:  2
Enter no. of rows:  2
Enter no. of cols:  2
Enter value:depth0 4 1 2 3 4
Enter value:depth1 4 1 2 3 4



Created Array:
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

                  Choose Mathematical Operation
                  1.Addition 
                  2.Subtraction
                  3.multiplication
                  4.Division
                  5.Dot Product
                  6.Matrix Multiplication
                  


Enter a operation:  1


Result:
 [[[2 4]
  [6 8]]

 [[2 4]
  [6 8]]]

        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


Enter choice:  2


Create second array:
Select type of Array to Create:
              1.1D array
              2.2D array
              3.3D array
              


Enter your choice:  3
Enter no. of depth:  2
Enter no. of rows:  2
Enter no. of cols:  2
Enter value:depth0 4 1 2 3 4
Enter value:depth1 4 1 2 3 4



Created Array:
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

                  Choose Mathematical Operation
                  1.Addition 
                  2.Subtraction
                  3.multiplication
                  4.Division
                  5.Dot Product
                  6.Matrix Multiplication
                  


Enter a operation:  6


Result:
 [[[ 7 10]
  [15 22]]

 [[ 7 10]
  [15 22]]]

        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


Enter choice:  4


min: 1
max: 4
mean: 2.5
sum: 20
variance: 1.25
std_dev: 1.118033988749895
median: 2.5

        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


Enter choice:  3



              Choice of operation
              1.Search
              2.Sort
              3.Filter
              


Enter a choice:  1
Enter a value:  7


Result:
 (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


Enter choice:  3



              Choice of operation
              1.Search
              2.Sort
              3.Filter
              


Enter a choice:  2


Result:
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

        ===== NumPy Analyzer =====
        1. Create Array
        2. Math Operations
        3. Search / Sort / Filter
        4. Aggregations
        5. Exit
        


In [6]:
np.array(list(map(lambda a: int(a),input("Enter a numb").split(" "))))

array([10, 20, 30, 40])

In [11]:
row = int(input("Enter Row"))
col = int(input("Enter col"))
enterElemt = row * col
lst = list(map(int, input(f"Enter value:{enterElemt} ").split(" ")))
array2d = np.array(lst).reshape(row, col)


In [12]:
array2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
noOf2Ddep = int(input("Enter no. of depth: "))
noOfRow = int(input("Enter no. of rows: "))
noOfCol = int(input("Enter no. of cols: "))
expectValue = noOfRow * noOfCol
print(expectValue)
matrix3D = []
for i in range(noOf2Ddep):
    lst = list(map(int, input(f"Enter value:depth{i} {expectValue}").split(" ")))
    arr2d = np.array(lst).reshape(noOfRow,noOfCol)
    matrix3D.append(array2d)

arr3d = np.array(matrix3D)
print(arr3d)
    


4
[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [24]:
arr1.get_array()

array([10, 10, 10, 10])

In [25]:
arr2.get_array()

array([[10, 20],
       [30, 40]])

In [28]:
arr1.get_array()

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [29]:
np.size(arr1.get_array())

27

In [30]:
np.shape(arr1.get_array())

(3, 3, 3)

In [1]:
print(arr1.get_array())

NameError: name 'arr1' is not defined

In [9]:
arr1.get_array() - arr2.get_array()

array([[[-4, -4],
        [-4, -4]],

       [[-4, -4],
        [-4, -4]]])

In [10]:
arr1.get_array()

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [11]:
arr2.get_array()

array([[[5, 6],
        [7, 8]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr2.get_array() - arr1.get_array()

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])